language: java
sudo: required
jdk:
  - openjdk8

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=IC-2020.2 # Current
  - IDEA_VERSION=IC-2019.1 # Minimum Supported

install: true

script:
  # Generate a gradle wrapper using a null gradle file so gradle < 4.6 does not fail parsing 'useJUnitPlatform()'.
  - touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 5.3 ; rm null.gradle
  - ./gradlew --version
  # Use the gradle wrapper to build and test the project.
  - ./gradlew :assemble
  - ./gradlew test
