language: java
sudo: required
jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=IC-2017.1
  - IDEA_VERSION=IC-2016.3
  - IDEA_VERSION=IC-2016.1.3

# Code Coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
