title: IntelliJ XQuery
email: msclrhd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/xquery-intellij-plugin"
github_user: rhdunn

language: en
stylesheet: /css/default.css

exclude:
  - images/features/error-recovery.xqy
  - images/features/vendor-extensions.xqy
  - images/features/xquery.xqy
  - Gemfile.lock
  - Gemfile
  - .gitignore

markdown: kramdown
plugins: []