name: build

on:
  push:
    branches:
      - master

env:
  XQT_PLATFORM: 'release'
  GRADLE_VERSION: 8.9

jobs:
  plugin:
    strategy:
      fail-fast: false
      matrix:
        idea-version: [
            IC-2022.1,
            IC-2022.2,
            IC-2022.3,
            IC-2023.1,
            IC-2023.2,
            IC-2023.3,
            IC-2024.1,
            IC-2024.2,
            LATEST-EAP-SNAPSHOT
        ]
        include:

          - java-version: 11
            idea-version: IC-2022.1

          - java-version: 11
            idea-version: IC-2022.2

          - java-version: 17
            idea-version: IC-2022.3

          - java-version: 17
            idea-version: IC-2023.1

          - java-version: 17
            idea-version: IC-2023.2

          - java-version: 17
            idea-version: IC-2023.3

          - java-version: 17
            idea-version: IC-2024.1

          - java-version: 21
            idea-version: IC-2024.2

          - java-version: 21
            idea-version: LATEST-EAP-SNAPSHOT

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IDEA_VERSION: ${{ matrix.idea-version }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Download XQT Platform Artifacts
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: actions/download-artifact@v3
        with:
          name: xqt-platform-jvm-${{ matrix.java-version }}

      - name: Extract XQT Platform Artifacts to Maven Local
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: |
          mkdir -p ~/.m2/repository/xqt-platform
          tar -xvf xqt-platform-jvm-${{ matrix.java-version }}.tar -C ~/.m2/repository/xqt-platform

      - name: Build
        run: gradle :assemble

      - name: Run Tests
        run: gradle test

      - name: Build Plugin
        run: gradle buildPlugin

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: xquery-intellij-plugin-${{ matrix.idea-version }}
          path: build/distributions/xquery-intellij-plugin-*.zip
