name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idea-version: [
            IC-2020.3,
            IC-2021.1,
            IC-2021.2,
            IC-2021.3,
            IC-2022.1,
            IC-2022.2,
            LATEST-EAP-SNAPSHOT
        ]
        include:

          - java-version: 11
            idea-version: IC-2020.3

          - java-version: 11
            idea-version: IC-2021.1

          - java-version: 11
            idea-version: IC-2021.2

          - java-version: 11
            idea-version: IC-2021.3

          - java-version: 11
            idea-version: IC-2022.1

          - java-version: 11
            idea-version: IC-2022.2

          - java-version: 17
            idea-version: LATEST-EAP-SNAPSHOT

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IDEA_VERSION: ${{ matrix.idea-version }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Create a Gradle Wrapper
        # Use a null gradle file so that if the gradle version cannot parse this gradle
        # file it will be able to run and generate the gradle wrapper.
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 7.5 ; rm null.gradle

      - name: Gradle Version
        run: ./gradlew --version

      - name: Build
        run: ./gradlew :assemble

      - name: Run Tests
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: xquery-intellij-plugin-${{ matrix.idea-version }}
          path: build/distributions/xquery-intellij-plugin-*.zip
