name: build

on:
  push:
    branches:
      - master

jobs:
  xqt-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Source Code Checkout
        uses: actions/checkout@v3
        with:
          repository: rhdunn/xqt-platform

      - name: Create a Gradle Wrapper
        # Use a null gradle file so that if the gradle version cannot parse this gradle
        # file it will be able to run and generate the gradle wrapper.
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 7.5 ; rm null.gradle

      - name: Gradle Version
        run: ./gradlew --version

      - name: Build for Kotlin/JVM
        run: ./gradlew -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: ./gradlew -D jvm.target=${{ matrix.java }} jvmTest

      - name: Publish Kotlin/Multiplatform to Maven Local
        run: ./gradlew -D jvm.target=${{ matrix.java }} publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/JVM to Maven Local
        run: ./gradlew -D jvm.target=${{ matrix.java }} publishJvmPublicationToMavenLocal

      - name: Tar XQT Platform Artifacts
        run: tar -cvf xqt-platform-jvm-${{ matrix.java }}.tar -C ~/.m2/repository/xqt-platform .

      - name: Upload XQT Platform Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xqt-platform-jvm-${{ matrix.java }}
          path: xqt-platform-jvm-${{ matrix.java }}.tar

  plugin:
    needs: xqt-platform
    strategy:
      fail-fast: false
      matrix:
        idea-version: [
            IC-2020.3,
            IC-2021.1,
            IC-2021.2,
            IC-2021.3,
            IC-2022.1,
            IC-2022.2,
            IC-2022.3,
            LATEST-EAP-SNAPSHOT
        ]
        include:

          - java-version: 11
            idea-version: IC-2020.3

          - java-version: 11
            idea-version: IC-2021.1

          - java-version: 11
            idea-version: IC-2021.2

          - java-version: 11
            idea-version: IC-2021.3

          - java-version: 11
            idea-version: IC-2022.1

          - java-version: 11
            idea-version: IC-2022.2

          - java-version: 17
            idea-version: IC-2022.3

          - java-version: 17
            idea-version: LATEST-EAP-SNAPSHOT

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IDEA_VERSION: ${{ matrix.idea-version }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Create a Gradle Wrapper
        # Use a null gradle file so that if the gradle version cannot parse this gradle
        # file it will be able to run and generate the gradle wrapper.
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 7.5 ; rm null.gradle

      - name: Gradle Version
        run: ./gradlew --version

      - name: Download XQT Platform Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-platform-jvm-${{ matrix.java-version }}

      - name: Extract XQT Platform Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/xqt-platform
          tar -xvf xqt-platform-jvm-${{ matrix.java-version }}.tar -C ~/.m2/repository/xqt-platform

      - name: Build
        run: ./gradlew :assemble

      - name: Run Tests
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: xquery-intellij-plugin-${{ matrix.idea-version }}
          path: build/distributions/xquery-intellij-plugin-*.zip
