name: check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

        # Use a null gradle file so gradle < 4.6 does not fail parsing 'useJUnitPlatform()'.
      - name: Create a gradle wrapper
        run: touch null.gradle ; gradle -b null.gradle wrapper --gradle-version 5.3 ; rm null.gradle

      - name: Gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew :assemble

      - name: Tests
        run: ./gradlew test
